### ISSUE TITLE
Doesn't update some dependencies?

### ISSUE THREAD

**Issue by connerxyz** [mousabaker/poetry-plugin-up#30]
I was happy to discover this plugin. It did update a good portion of dependencies in `pyproject.toml` running `poetry up --latest`.

However, I noticed some dependencies were not updated:

- `poethepoet`
- `mockito`

So, I removed these packages and re-added them to see if there was a later compatible version.

```
remove poethepoet
poetry add poethepoet@latest
remove mockito
poetry add mockito
```

...which did result in updating these dependency versions.

```
Updating poethepoet (0.8.0 -> 0.24.0)
Updating mockito (1.2.2 -> 1.4.0)
```

Is this expected behavior? (Perhaps there is something about how this plugin works I don't understand?) I expected all the packages to be update to their latest compatible versions.

Thanks

**Comment by mousabaker** [comment]
Glad you like the project.

This plugin is supposed to update all packages (unless some are excluded). Its important to say that its `poetry` itself that makes the update, this plugin simply manages them and make sure to bump `pyproject.toml` file. If a package is not updated, then most likely its due to incompatible versions. For instance [poethepoet](https://github.com/nat-n/poethepoet/blob/main/pyproject.toml#L15) depends on `tomlkit = "^0.7.0"` and [poetry](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L56) itself depends on `tomlkit = ">=0.11.4,<1.0.0"`.
